# global
#threads=32
time=120
warmup_time=0
report_interval=5
verbosity=3
db_driver=mysql

#mysql
mysql_host=127.0.0.1
mysql_port=3306
mysql_user=sysbench
mysql_password="sysbench_pass"
mysql_db=sysbench

#[oltp_common]
table_size=1000000
tables=10

#[oltp_point_select]
point_selects=1

# read_only
sum_ranges=50
distinct_ranges=50
range_size=100
simple_ranges=100
order_ranges=100

# update_index
index_updates=1

# insert/delete
delete_inserts=1
